### PR TITLE
Attempted to work on Stage Preview

### PR DESCRIPTION
**Pull request by lufinkey**
I need some help on this. I'm stumped.

### CODE REVIEW

**Comment by Kfeavel** [comment]
Ah, didn't see that comment on the music part. Also, what code am I looping?

**Comment by Kfeavel** [comment]
Also, like the new Intro background?

**Comment by lufinkey** [comment]
Yeah, but we should definitely focus more on programming. No offense, but
we can totally worry about assets later. I'm only putting in the minimum
needed for testing right now

**Comment by Kfeavel** [comment]
Yeah, sorry. I kind of get carried away with assets before code when making games.

**Comment by lufinkey** [comment]
it's totally fine. I just want to get the main part done. I think I fixed the StageSelectScreen code. I just have to get the preview to show

**Pull request merged**
