### PR TITLE
Located Crash

### PR DESCRIPTION
**Pull request by Kfeavel**
Game crashes on line 109 of src/GameLibrary/Screen/MenuScreen.cpp

### CODE REVIEW

**Comment by Kfeavel** [comment]
Just now saw that you fixed the crash. I'll update my fork and resubmit.

**Comment by lufinkey** [comment]
I fixed a few other things just now as well. I'm still cleaning up a bunch of bugs. Also, I didn't add the old sound engine because I want to rewrite it. I'm probably going to use a different library for it.

**Comment by Kfeavel** [comment]
Sounds good. I'll keep my fork up to date and keep an eye out for anything I can help fix. I've also noticed that the game doesn't always like to start on iOS.

**Comment by lufinkey** [comment]
what do you mean?

**Comment by Kfeavel** [comment]
When I open the app, it just likes to sit at the Smash Bros X screen indefinitely.

**Comment by lufinkey** [comment]
Yeah I'm still fixing iOS issues

**Comment by lufinkey** [comment]
I just fixed pretty much all of the iOS issues. Can you update your branch?

**Comment by Kfeavel** [comment]
Will do. I currently don't have my Mac on me so I'll do it tomorrow morning.
- Keeton Feavel

**Pull request closed without merging**
